name: Intentional Fail CI

on:
  push:
    branches: ["main"]

jobs:
  fail-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Step sukses dulu
        run: echo "step ini aman ğŸ‘"

      - name: FAIL SENGAJA
        run: |
          echo "ğŸ”¥ ini sengaja gagal"
          exit 1